[package]
name = "async-fetcher"
version = "0.1.1-alpha.0"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Asynchronous file fetcher with optional fetching based on modified times and checksums"
keywords = ["async", "file", "fetcher", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MIT"
readme = "README.md"

[dependencies]
chrono = "0.4.6"
digest = "0.8.0"
filetime = "0.2.4"
futures = "0.1.25"
hex-view = "0.1.2"
log = "0.4.6"
reqwest = "0.9.5"
tokio = "0.1.13"

# Fix build for 1.28.0
encoding_rs = "=0.8.9"

[dev-dependencies]
flate2 = "1.0.5"
sha2 = "0.8.0"
xz2 = "0.1.6"
