[package]
name = "async-fetcher"
version = "0.3.0-alpha.2"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Asynchronous file fetcher, with optional fetching based on modified times and checksums"
keywords = ["async", "file", "fetcher", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
async-std = "1"
chrono = "0.4"
derive-new = "0"
filetime = "0.2"
futures = "0.3"
http = "0.1"
log = "0.4"
numtoa = "0.2"
thiserror = "1"

# surf = "1"
# surf = { git = "https://github.com/http-rs/surf" }
# http-client = "1"

surf = { git = "https://github.com/mmstick/surf" }
http-client = { git = "https://github.com/mmstick/http-client" }
