[package]
name = "async-fetcher"
version = "0.6.2"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
description = "Asynchronous multi-connection multi-download resumable HTTP file fetching state machine"
keywords = ["async", "file", "fetch", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MPL-2.0"
readme = "README.md"
edition = "2018"

[workspace]
members = [ "fetcher" ]

[dependencies]
derive_more = "0.99"
derive_setters = "0.1"
derive-new = "0.5"
digest = "0.10"
filetime = "0.2"
futures = "0.3"
hex = "0.4"
httpdate = "1.0"
log = "0.4"
md-5 = "0.10"
numtoa = "0.2"
remem = "0.1"
sha2 = "0.10"
thiserror = "1.0"
isahc = "1.6"
http = "0.2"
once_cell = "1.9.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.16"
features = ["fs", "io-util", "rt", "sync", "time"]
