[package]
name = "async-fetcher"
version = "0.3.0-alpha.3"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
description = "Asynchronous file fetcher, with optional fetching based on modified times and checksums"
keywords = ["async", "file", "fetcher", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MPL-2.0"
readme = "README.md"
edition = "2018"

[workspace]
members = [ "fetcher" ]

[dependencies]
async-stream = "0.3.2"
derive_more = "0.99.17"
derive_setters = "0.1.5"
derive-new = "0.5.9"
digest = "0.10.1"
filetime = "0.2.15"
futures = "0.3.19"
hex = "0.4.3"
httpdate = "1.0.2"
log = "0.4.14"
md-5 = "0.10.0"
numtoa = "0.2.4"
remem = "0.1.0"
serde = { version = "1.0.136", features = [ "derive" ] }
sha2 = "0.10.1"
thiserror = "1.0.30"
async-fs = "1.5.0"
async-io = "1.6.0"
isahc = "1.6.0"
http = "0.2.6"
