[package]
name = "async-fetcher"
version = "0.3.0-alpha.2"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Asynchronous file fetcher, with optional fetching based on modified times and checksums"
keywords = ["async", "file", "fetcher", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
chrono = "0.4"
filetime = "0.2"
futures = "0.3"
numtoa = "0.2"
thiserror = "1"
derive-new = "0"
async-std = "1"
http = "0.1"
surf = { git = "https://github.com/pwoolcoc/surf", branch = "move-to-http-client" }
http-client = { git = "https://github.com/pwoolcoc/http-client", branch = "issue-5-port-to-futures-0-3", features = ["native_client"] }
