[package]
name = "fetcher"
version = "0.4.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
async-fetcher = { path = "../" }
atty = "0.2"
better-panic = "0.3"
fomat-macros = "0.3"
futures = "0.3"
pbr = "1.0"
ron = "0.7"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0"
bytes = "1.1"
console-subscriber = "0.1"
tokio-stream = "0.1"

[dependencies.tokio-util]
version = "0.6"
features = ["codec"]

[dependencies.tokio]
version = "1.16"
features = ["full"]
