[package]
name = "fetcher"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fetcher = { path = "../" }
async-fs = "1.5.0"
async-io = "1.6.0"
atty = "0.2.14"
better-panic = "0.2.0"
blocking = "1.1.0"
fomat-macros = "0.3.1"
futures = "0.3.18"
futures_codec = "0.4.1"
pbr = "1.0.4"
ron = "0.7.0"
serde = { version = "1.0.131", features = [ "derive" ] }
surf = "2.3.2"
thiserror = "1.0.30"
tokio = "1.14.0"
